<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment Receipt</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            font-size: 12pt;
        }

        .receipt-container {
            max-width: 800px;
            margin: 0 auto;
            border: 1px solid #ccc;
            padding: 20px;
            background: #fff;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header img {
            max-width: 150px;
        }

        .company-info, .payer-info, .payment-details, .dues-table, .footer {
            margin-bottom: 20px;
        }

        .company-info p, .payer-info p, .payment-details p {
            margin: 5px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
        }

        th {
            background: #f4f4f4;
        }

        .total {
            font-weight: bold;
        }

        .footer {
            text-align: center;
            font-size: 10pt;
            color: #666;
        }

        @media print {
            body {
                margin: 0;
            }

            .receipt-container {
                border: none;
            }
        }
    </style>
</head>
<body onload="window.print()">
<div class="receipt-container">
    <div class="header">
        @if($company_info['logo'])
            <img src="{{ $company_info['logo'] }}" alt="{{ $company_info['name'] }} Logo">
        @endif
        <h2>{{ $company_info['name'] }}</h2>
        <p>{{ $company_info['address'] }}</p>
        <p>Phone: {{ $company_info['phone'] }} | Email: {{ $company_info['email'] }}</p>
        <p>Website: {{ $company_info['website'] }}</p>
    </div>

    <h3>Payment Receipt</h3>
    <p>Receipt Number: {{ $receipt_number }}</p>
    <p>Generated At: {{ $generated_at->format(config('receipt.date_format', 'M d, Y h:i A')) }}</p>

    <div class="payer-info">
        <h4>Payer Information</h4>
        <p>Name: {{ $user->first_name }} {{ $user->family_name }}</p>
        <p>Email: {{ $user->email }}</p>
        @if($user->prc_registration_number)
            <p>PRC Registration: {{ $user->prc_registration_number }}</p>
        @endif
    </div>

    <div class="payment-details">
        <h4>Payment Details</h4>
        <p>Transaction Reference: {{ $transaction->transaction_reference }}</p>
        <p>Payment Method: {{ $transaction->payment_method }}</p>
        <p>
            Amount: {{ number_format($transaction->amount, config('receipt.number_format.decimals', 2), config('receipt.number_format.decimal_separator', '.'), config('receipt.number_format.thousands_separator', ',')) }} {{ $transaction->currency }}</p>
        <p>Payment
            Date: {{ ($transaction->completed_at ?? $transaction->created_at)->format(config('receipt.date_format', 'M d, Y h:i A')) }}</p>
    </div>

    <div class="dues-table">
        <h4>Dues Paid</h4>
        <table>
            <thead>
            <tr>
                <th>Description</th>
                <th>Amount</th>
                <th>Due Date</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody>
            @foreach($dues as $due)
                <tr>
                    <td>{{ $due->description }}</td>
                    <td>{{ number_format($due->amount, config('receipt.number_format.decimals', 2), config('receipt.number_format.decimal_separator', '.'), config('receipt.number_format.thousands_separator', ',')) }} {{ $transaction->currency }}</td>
                    <td>{{ $due->due_date->format('M d, Y') }}</td>
                    <td>{{ ucfirst($due->status) }}</td>
                </tr>
            @endforeach
            <tr>
                <td class="total">Total</td>
                <td class="total">{{ number_format($transaction->amount, config('receipt.number_format.decimals', 2), config('receipt.number_format.decimal_separator', '.'), config('receipt.number_format.thousands_separator', ',')) }} {{ $transaction->currency }}</td>
                <td colspan="2"></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>Thank you for your payment!</p>
        <p>This is an official receipt generated by {{ $company_info['name'] }}.</p>
    </div>
</div>

<script>
    window.onload = function () {
        window.print();
        // Close the window after printing (optional, comment out if not desired)
        // setTimeout(() => window.close(), 500);
    };
</script>
</body>
</html>
